# version: '3'

# services:
#   server:
#     container_name: server
#     environment:
#       - FLASK_APP=server:create_app()
#       - FLASK_DEBUG=1
#     volumes:
#       - ./project:/src/
#     command: flask run --host=0.0.0.0

#   worker:
#     container_name: worker
#     volumes:
#       - ./project:/src

#   dashboard:
#     container_name: dashboard

#   redis:
#     container_name: redis

version: '3'
services:
  server:
    container_name: server
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: 1
  redis:
    image: "redis:alpine"